/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesTicketsRouteImport } from './routes/mes-tickets'
import { Route as AchatIdRouteImport } from './routes/achat.$id'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConnexionRouteImport } from './routes/admin.connexion'
import { Route as AdminEvenementsRouteImport } from './routes/admin.evenements'
import { Route as AdminOrganisateursRouteImport } from './routes/admin.organisateurs'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as AdminRetraitsRouteImport } from './routes/admin.retraits'
import { Route as EvenementIdRouteImport } from './routes/evenement.$id'
import { Route as OrganisateurIndexRouteImport } from './routes/organisateur.index'
import { Route as OrganisateurAgentsRouteImport } from './routes/organisateur.agents'
import { Route as OrganisateurConnexionRouteImport } from './routes/organisateur.connexion'
import { Route as OrganisateurEvenementsRouteImport } from './routes/organisateur.evenements'
import { Route as OrganisateurInscriptionRouteImport } from './routes/organisateur.inscription'
import { Route as OrganisateurNouveauRouteImport } from './routes/organisateur.nouveau'
import { Route as OrganisateurRetraitRouteImport } from './routes/organisateur.retrait'
import { Route as OrganisateurVentesRouteImport } from './routes/organisateur.ventes'
import { Route as OrganisateurWalletRouteImport } from './routes/organisateur.wallet'
import { Route as ScannerIndexRouteImport } from './routes/scanner.index'
import { Route as ScannerConnexionRouteImport } from './routes/scanner.connexion'
import { Route as TicketCodeRouteImport } from './routes/ticket.$code'
import { Route as OrganisateurEvenementIdRouteImport } from './routes/organisateur.evenement.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesTicketsRoute = MesTicketsRouteImport.update({
  id: '/mes-tickets',
  path: '/mes-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatIdRoute = AchatIdRouteImport.update({
  id: '/achat/$id',
  path: '/achat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnexionRoute = AdminConnexionRouteImport.update({
  id: '/admin/connexion',
  path: '/admin/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvenementsRoute = AdminEvenementsRouteImport.update({
  id: '/admin/evenements',
  path: '/admin/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganisateursRoute = AdminOrganisateursRouteImport.update({
  id: '/admin/organisateurs',
  path: '/admin/organisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/admin/paiements',
  path: '/admin/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetraitsRoute = AdminRetraitsRouteImport.update({
  id: '/admin/retraits',
  path: '/admin/retraits',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementIdRoute = EvenementIdRouteImport.update({
  id: '/evenement/$id',
  path: '/evenement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurIndexRoute = OrganisateurIndexRouteImport.update({
  id: '/organisateur/',
  path: '/organisateur/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurAgentsRoute = OrganisateurAgentsRouteImport.update({
  id: '/organisateur/agents',
  path: '/organisateur/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurConnexionRoute = OrganisateurConnexionRouteImport.update({
  id: '/organisateur/connexion',
  path: '/organisateur/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurEvenementsRoute = OrganisateurEvenementsRouteImport.update({
  id: '/organisateur/evenements',
  path: '/organisateur/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurInscriptionRoute = OrganisateurInscriptionRouteImport.update({
  id: '/organisateur/inscription',
  path: '/organisateur/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurNouveauRoute = OrganisateurNouveauRouteImport.update({
  id: '/organisateur/nouveau',
  path: '/organisateur/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurRetraitRoute = OrganisateurRetraitRouteImport.update({
  id: '/organisateur/retrait',
  path: '/organisateur/retrait',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurVentesRoute = OrganisateurVentesRouteImport.update({
  id: '/organisateur/ventes',
  path: '/organisateur/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurWalletRoute = OrganisateurWalletRouteImport.update({
  id: '/organisateur/wallet',
  path: '/organisateur/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerIndexRoute = ScannerIndexRouteImport.update({
  id: '/scanner/',
  path: '/scanner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerConnexionRoute = ScannerConnexionRouteImport.update({
  id: '/scanner/connexion',
  path: '/scanner/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCodeRoute = TicketCodeRouteImport.update({
  id: '/ticket/$code',
  path: '/ticket/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateurEvenementIdRoute = OrganisateurEvenementIdRouteImport.update({
  id: '/organisateur/evenement/$id',
  path: '/organisateur/evenement/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mes-tickets': typeof MesTicketsRoute
  '/achat/$id': typeof AchatIdRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/organisateurs': typeof AdminOrganisateursRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/retraits': typeof AdminRetraitsRoute
  '/evenement/$id': typeof EvenementIdRoute
  '/organisateur/agents': typeof OrganisateurAgentsRoute
  '/organisateur/connexion': typeof OrganisateurConnexionRoute
  '/organisateur/evenements': typeof OrganisateurEvenementsRoute
  '/organisateur/inscription': typeof OrganisateurInscriptionRoute
  '/organisateur/nouveau': typeof OrganisateurNouveauRoute
  '/organisateur/retrait': typeof OrganisateurRetraitRoute
  '/organisateur/ventes': typeof OrganisateurVentesRoute
  '/organisateur/wallet': typeof OrganisateurWalletRoute
  '/scanner/connexion': typeof ScannerConnexionRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/organisateur/': typeof OrganisateurIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/organisateur/evenement/$id': typeof OrganisateurEvenementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mes-tickets': typeof MesTicketsRoute
  '/achat/$id': typeof AchatIdRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/organisateurs': typeof AdminOrganisateursRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/retraits': typeof AdminRetraitsRoute
  '/evenement/$id': typeof EvenementIdRoute
  '/organisateur/agents': typeof OrganisateurAgentsRoute
  '/organisateur/connexion': typeof OrganisateurConnexionRoute
  '/organisateur/evenements': typeof OrganisateurEvenementsRoute
  '/organisateur/inscription': typeof OrganisateurInscriptionRoute
  '/organisateur/nouveau': typeof OrganisateurNouveauRoute
  '/organisateur/retrait': typeof OrganisateurRetraitRoute
  '/organisateur/ventes': typeof OrganisateurVentesRoute
  '/organisateur/wallet': typeof OrganisateurWalletRoute
  '/scanner/connexion': typeof ScannerConnexionRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/admin': typeof AdminIndexRoute
  '/organisateur': typeof OrganisateurIndexRoute
  '/scanner': typeof ScannerIndexRoute
  '/organisateur/evenement/$id': typeof OrganisateurEvenementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mes-tickets': typeof MesTicketsRoute
  '/achat/$id': typeof AchatIdRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/organisateurs': typeof AdminOrganisateursRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/retraits': typeof AdminRetraitsRoute
  '/evenement/$id': typeof EvenementIdRoute
  '/organisateur/agents': typeof OrganisateurAgentsRoute
  '/organisateur/connexion': typeof OrganisateurConnexionRoute
  '/organisateur/evenements': typeof OrganisateurEvenementsRoute
  '/organisateur/inscription': typeof OrganisateurInscriptionRoute
  '/organisateur/nouveau': typeof OrganisateurNouveauRoute
  '/organisateur/retrait': typeof OrganisateurRetraitRoute
  '/organisateur/ventes': typeof OrganisateurVentesRoute
  '/organisateur/wallet': typeof OrganisateurWalletRoute
  '/scanner/connexion': typeof ScannerConnexionRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/organisateur/': typeof OrganisateurIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/organisateur/evenement/$id': typeof OrganisateurEvenementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mes-tickets'
    | '/achat/$id'
    | '/admin/connexion'
    | '/admin/evenements'
    | '/admin/organisateurs'
    | '/admin/paiements'
    | '/admin/retraits'
    | '/evenement/$id'
    | '/organisateur/agents'
    | '/organisateur/connexion'
    | '/organisateur/evenements'
    | '/organisateur/inscription'
    | '/organisateur/nouveau'
    | '/organisateur/retrait'
    | '/organisateur/ventes'
    | '/organisateur/wallet'
    | '/scanner/connexion'
    | '/ticket/$code'
    | '/admin/'
    | '/organisateur/'
    | '/scanner/'
    | '/organisateur/evenement/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mes-tickets'
    | '/achat/$id'
    | '/admin/connexion'
    | '/admin/evenements'
    | '/admin/organisateurs'
    | '/admin/paiements'
    | '/admin/retraits'
    | '/evenement/$id'
    | '/organisateur/agents'
    | '/organisateur/connexion'
    | '/organisateur/evenements'
    | '/organisateur/inscription'
    | '/organisateur/nouveau'
    | '/organisateur/retrait'
    | '/organisateur/ventes'
    | '/organisateur/wallet'
    | '/scanner/connexion'
    | '/ticket/$code'
    | '/admin'
    | '/organisateur'
    | '/scanner'
    | '/organisateur/evenement/$id'
  id:
    | '__root__'
    | '/'
    | '/mes-tickets'
    | '/achat/$id'
    | '/admin/connexion'
    | '/admin/evenements'
    | '/admin/organisateurs'
    | '/admin/paiements'
    | '/admin/retraits'
    | '/evenement/$id'
    | '/organisateur/agents'
    | '/organisateur/connexion'
    | '/organisateur/evenements'
    | '/organisateur/inscription'
    | '/organisateur/nouveau'
    | '/organisateur/retrait'
    | '/organisateur/ventes'
    | '/organisateur/wallet'
    | '/scanner/connexion'
    | '/ticket/$code'
    | '/admin/'
    | '/organisateur/'
    | '/scanner/'
    | '/organisateur/evenement/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MesTicketsRoute: typeof MesTicketsRoute
  AchatIdRoute: typeof AchatIdRoute
  AdminConnexionRoute: typeof AdminConnexionRoute
  AdminEvenementsRoute: typeof AdminEvenementsRoute
  AdminOrganisateursRoute: typeof AdminOrganisateursRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminRetraitsRoute: typeof AdminRetraitsRoute
  EvenementIdRoute: typeof EvenementIdRoute
  OrganisateurAgentsRoute: typeof OrganisateurAgentsRoute
  OrganisateurConnexionRoute: typeof OrganisateurConnexionRoute
  OrganisateurEvenementsRoute: typeof OrganisateurEvenementsRoute
  OrganisateurInscriptionRoute: typeof OrganisateurInscriptionRoute
  OrganisateurNouveauRoute: typeof OrganisateurNouveauRoute
  OrganisateurRetraitRoute: typeof OrganisateurRetraitRoute
  OrganisateurVentesRoute: typeof OrganisateurVentesRoute
  OrganisateurWalletRoute: typeof OrganisateurWalletRoute
  ScannerConnexionRoute: typeof ScannerConnexionRoute
  TicketCodeRoute: typeof TicketCodeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrganisateurIndexRoute: typeof OrganisateurIndexRoute
  ScannerIndexRoute: typeof ScannerIndexRoute
  OrganisateurEvenementIdRoute: typeof OrganisateurEvenementIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-tickets': {
      id: '/mes-tickets'
      path: '/mes-tickets'
      fullPath: '/mes-tickets'
      preLoaderRoute: typeof MesTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achat/$id': {
      id: '/achat/$id'
      path: '/achat/$id'
      fullPath: '/achat/$id'
      preLoaderRoute: typeof AchatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connexion': {
      id: '/admin/connexion'
      path: '/admin/connexion'
      fullPath: '/admin/connexion'
      preLoaderRoute: typeof AdminConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evenements': {
      id: '/admin/evenements'
      path: '/admin/evenements'
      fullPath: '/admin/evenements'
      preLoaderRoute: typeof AdminEvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organisateurs': {
      id: '/admin/organisateurs'
      path: '/admin/organisateurs'
      fullPath: '/admin/organisateurs'
      preLoaderRoute: typeof AdminOrganisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/admin/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/retraits': {
      id: '/admin/retraits'
      path: '/admin/retraits'
      fullPath: '/admin/retraits'
      preLoaderRoute: typeof AdminRetraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenement/$id': {
      id: '/evenement/$id'
      path: '/evenement/$id'
      fullPath: '/evenement/$id'
      preLoaderRoute: typeof EvenementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/': {
      id: '/organisateur/'
      path: '/organisateur'
      fullPath: '/organisateur/'
      preLoaderRoute: typeof OrganisateurIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/agents': {
      id: '/organisateur/agents'
      path: '/organisateur/agents'
      fullPath: '/organisateur/agents'
      preLoaderRoute: typeof OrganisateurAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/connexion': {
      id: '/organisateur/connexion'
      path: '/organisateur/connexion'
      fullPath: '/organisateur/connexion'
      preLoaderRoute: typeof OrganisateurConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/evenements': {
      id: '/organisateur/evenements'
      path: '/organisateur/evenements'
      fullPath: '/organisateur/evenements'
      preLoaderRoute: typeof OrganisateurEvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/inscription': {
      id: '/organisateur/inscription'
      path: '/organisateur/inscription'
      fullPath: '/organisateur/inscription'
      preLoaderRoute: typeof OrganisateurInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/nouveau': {
      id: '/organisateur/nouveau'
      path: '/organisateur/nouveau'
      fullPath: '/organisateur/nouveau'
      preLoaderRoute: typeof OrganisateurNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/retrait': {
      id: '/organisateur/retrait'
      path: '/organisateur/retrait'
      fullPath: '/organisateur/retrait'
      preLoaderRoute: typeof OrganisateurRetraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/ventes': {
      id: '/organisateur/ventes'
      path: '/organisateur/ventes'
      fullPath: '/organisateur/ventes'
      preLoaderRoute: typeof OrganisateurVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/wallet': {
      id: '/organisateur/wallet'
      path: '/organisateur/wallet'
      fullPath: '/organisateur/wallet'
      preLoaderRoute: typeof OrganisateurWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/': {
      id: '/scanner/'
      path: '/scanner'
      fullPath: '/scanner/'
      preLoaderRoute: typeof ScannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/connexion': {
      id: '/scanner/connexion'
      path: '/scanner/connexion'
      fullPath: '/scanner/connexion'
      preLoaderRoute: typeof ScannerConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$code': {
      id: '/ticket/$code'
      path: '/ticket/$code'
      fullPath: '/ticket/$code'
      preLoaderRoute: typeof TicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateur/evenement/$id': {
      id: '/organisateur/evenement/$id'
      path: '/organisateur/evenement/$id'
      fullPath: '/organisateur/evenement/$id'
      preLoaderRoute: typeof OrganisateurEvenementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MesTicketsRoute: MesTicketsRoute,
  AchatIdRoute: AchatIdRoute,
  AdminConnexionRoute: AdminConnexionRoute,
  AdminEvenementsRoute: AdminEvenementsRoute,
  AdminOrganisateursRoute: AdminOrganisateursRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminRetraitsRoute: AdminRetraitsRoute,
  EvenementIdRoute: EvenementIdRoute,
  OrganisateurAgentsRoute: OrganisateurAgentsRoute,
  OrganisateurConnexionRoute: OrganisateurConnexionRoute,
  OrganisateurEvenementsRoute: OrganisateurEvenementsRoute,
  OrganisateurInscriptionRoute: OrganisateurInscriptionRoute,
  OrganisateurNouveauRoute: OrganisateurNouveauRoute,
  OrganisateurRetraitRoute: OrganisateurRetraitRoute,
  OrganisateurVentesRoute: OrganisateurVentesRoute,
  OrganisateurWalletRoute: OrganisateurWalletRoute,
  ScannerConnexionRoute: ScannerConnexionRoute,
  TicketCodeRoute: TicketCodeRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrganisateurIndexRoute: OrganisateurIndexRoute,
  ScannerIndexRoute: ScannerIndexRoute,
  OrganisateurEvenementIdRoute: OrganisateurEvenementIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
